
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:~/var/lib/upload/upload
    username: admin
    password: admin
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
    ddl-auto: update

server:
  port: 10003
